# Generated by Django 3.2.9 on 2021-11-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csoport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kreta', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Csoport',
                'verbose_name_plural': 'Csoportok',
            },
        ),
        migrations.CreateModel(
            name='Munkakozosseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('nev', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Munkaközösség',
                'verbose_name_plural': 'Munkaközösségek',
            },
        ),
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('hosszu', models.CharField(max_length=20)),
                ('rovid', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Nap',
                'verbose_name_plural': 'Napok',
            },
        ),
        migrations.CreateModel(
            name='Osztaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('kreta', models.CharField(max_length=50)),
                ('evfolyam', models.CharField(max_length=5)),
                ('kor', models.CharField(max_length=5)),
                ('szekcio', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Osztály',
                'verbose_name_plural': 'Osztályok',
            },
        ),
        migrations.CreateModel(
            name='Szarny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('hosszu', models.CharField(max_length=20)),
                ('rovid', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Szárny',
                'verbose_name_plural': 'Szárnyak',
            },
        ),
        migrations.CreateModel(
            name='Tanar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('kreta', models.CharField(max_length=50)),
                ('hosszu', models.CharField(max_length=50)),
                ('rovid', models.CharField(max_length=20)),
                ('monogram', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tanár',
                'verbose_name_plural': 'Tanárok',
            },
        ),
        migrations.CreateModel(
            name='Tantargy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('kreta', models.CharField(max_length=50)),
                ('hosszu', models.CharField(max_length=20)),
                ('rovid', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tantárgy',
                'verbose_name_plural': 'Tantárgyak',
            },
        ),
        migrations.CreateModel(
            name='Terem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('kreta', models.CharField(max_length=50)),
                ('hosszu', models.CharField(max_length=50)),
                ('rovid', models.CharField(max_length=20)),
                ('emelet', models.IntegerField()),
                ('szarny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.szarny')),
            ],
            options={
                'verbose_name': 'Terem',
                'verbose_name_plural': 'Termek',
            },
        ),
        migrations.CreateModel(
            name='Ora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora', models.IntegerField()),
                ('csoport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.csoport')),
                ('nap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.nap')),
                ('tanar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.tanar')),
                ('tantargy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.tantargy')),
                ('terem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.terem')),
            ],
            options={
                'verbose_name': 'Óra',
                'verbose_name_plural': 'Óra',
            },
        ),
        migrations.CreateModel(
            name='MTK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munkakozosseg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.munkakozosseg')),
                ('tanar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.tanar')),
            ],
            options={
                'verbose_name': 'Munkaközösség-Tanar kapcsolat',
                'verbose_name_plural': 'Munkaközösség-Tanar kapcsolatok',
            },
        ),
        migrations.CreateModel(
            name='CSOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csoport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.csoport')),
                ('osztaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_orarend.osztaly')),
            ],
            options={
                'verbose_name': 'Csoport-Osztály kapcsolat',
                'verbose_name_plural': 'Csoport-Osztály kapcsolatok',
            },
        ),
    ]
