# Generated by Django 3.2.9 on 2021-11-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_osztaly_kor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csok',
            options={'verbose_name': 'Csoport-Osztály kapcsolat', 'verbose_name_plural': 'Csoport-Osztály kapcsolatok'},
        ),
    ]
