# Generated by Django 3.2.9 on 2021-11-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_csok_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Munkakozosseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorszam', models.IntegerField()),
                ('nev', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Munkaközösség',
                'verbose_name_plural': 'Munkaközösségek',
            },
        ),
        migrations.CreateModel(
            name='MTK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munkakozosseg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.munkakozosseg')),
                ('tanar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.tanar')),
            ],
            options={
                'verbose_name': 'Munkaközösség-Tanar kapcsolat',
                'verbose_name_plural': 'Munkaközösség-Tanar kapcsolatok',
            },
        ),
    ]
